kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: util-pv-claim
  namespace: magicdog
spec:
  storageClassName: magicdog
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
